#! /bin/bash

SWIM=/home/blueprin/shared/Swim
FCKeditor=/home/blueprin/shared/FCKeditor

mkdir swim
mkdir swim/admin
ln -s $SWIM/admin/static swim/admin/static
ln -s $SWIM/shared swim/shared
cp $SWIM/.htaccess .
ln -s $SWIM/swim.php swim.php
ln -s $SWIM/swim.php index.php
ln -s $SWIM/redirect.php redirect.php
ln -s $SWIM/cron.php cron.php

mkdir swim/branding
ln -s $SWIM/branding/static swim/branding/static

ln -s $FCKeditor FCKeditor
