#! /usr/bin/perl
use Time::Local;

$dir = $ARGV[0];
if (opendir(BACKUPS, $dir))
{
  $now = time();
  $weekold = $now-(7*24*60*60);
  while ($backup = readdir(BACKUPS))
  {
    if ($backup =~ m/backup-(\d{4})(\d{2})(\d{2})-(\d{2})(\d{2})\.tar\.gz/)
    {
      print($backup."\n");
      $time = timegm(0, $5, $4, $3, $2-1, $1);
      if ($time<$weekold)
      {
        unlink($dir.$backup);
      }
    }
  }
  closedir(BACKUPS);
}
